### ISSUE TITLE
SilkCodec.dll is missing in nuget package

### ISSUE THREAD

**Issue by Chronostasys** [KonataDev/Konata.Codec#1]
Hi, I'm trying to use Konata.Core to build my own qq bot. Whenever I try to send a piece of audio using the framwork, an exception occured.   
I cloned this repo and digged into it, seems like it's caused by the source below:  
https://github.com/KonataDev/Konata.Codec/blob/d221cb8954f654c72454b44a9c2fa5de07fa9b7e/Konata.Codec/Audio/Codecs/SilkV3Codec.cs#L17  

The code is trying to import `SilkCodec.dll`, which doesn't show up either in nuget package nor the source repo.

**Comment by TheSnowfield** [comment]
> Hi, I'm trying to use Konata.Core to build my own qq bot. Whenever I try to send a piece of audio using the framwork, an exception occured. I cloned this repo and digged into it, seems like it's caused by the source below:
> 
> https://github.com/KonataDev/Konata.Codec/blob/d221cb8954f654c72454b44a9c2fa5de07fa9b7e/Konata.Codec/Audio/Codecs/SilkV3Codec.cs#L17
> 
> The code is trying to import `SilkCodec.dll`, which doesn't show up either in nuget package nor the source repo.

Sorry for bringing trouble to you.
Cuz the binary file is hard to distribute in the cross-platform scheme. 
In the current situation, you have to build it from source-code and then put the dll under the Konata.Codec.dll folder.

**Comment by Chronostasys** [comment]
Thanks for the fast reply. Where can I find the source code for `SilkCodec.dll`?

**Comment by TheSnowfield** [comment]
> Thanks for the fast reply. Where can I find the source code for `SilkCodec.dll`?

https://github.com/KonataDev/libSilkCodec

**Comment by Chronostasys** [comment]
Thanks.
